name: Publish Naev Linux Docker Images
on: [push]

jobs:
  "Build_Ubuntu":
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            dockerfile: "naev/naev-ubuntu1604"
            tagname: naev-ubuntu1604
          - os: ubuntu-latest
            dockerfile: "naev/naev-ubuntu2004"
            tagname: naev-ubuntu2004
          - os: ubuntu-latest
            dockerfile: "naev/naev-steamruntime"
            tagname: naev-steamruntime
          - os: ubuntu-latest
            dockerfile: "naev/naev-windows"
            tagname: naev-windows

    runs-on: ${{ matrix.os }}

    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@master
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Copy Gemfile to context
        run: |
          cp naev/Gemfile ${{ matrix.dockerfile }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerfile }}
          file: ${{ matrix.dockerfile }}/Dockerfile
          push: true
          tags: projectsynchro/synchros_sexy_docker_images:${{ matrix.tagname }}
