name: Publish Naev Windows Docker Images
on: [push]

jobs:
  "Build_Windows":
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            dockerfile: "windows/naev-windows1909"
            tagname: naev-windows1909
          - os: windows-latest
            dockerfile: "windows/naev-windows2004"
            tagname: naev-windows2004

    runs-on: ${{ matrix.os }}

    steps:
      - 
        name: Checkout Repository
        uses: actions/checkout@master
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerfile }}
          file: ${{ matrix.dockerfile }}/Dockerfile
          push: true
          tags: projectsynchro/synchros_sexy_docker_images:${{ matrix.tagname }}
