name: Test Naev Build/Dev Docker Images
on: [push, pull_request]

jobs:
  "Build_Test_Images":
    strategy:
      fail-fast: true
      matrix:
        include:
          - context: "naev/naev-ubuntu1604"
            imagename: "naev-ubuntu1604"
          - context: "naev/naev-ubuntu2004"
            imagename: "naev-ubuntu2004"
          - context: "naev/naev-steamruntime"
            imagename: "naev-steamruntime"
          - context: "naev/naev-windows"
            imagename: "naev-windows"
          - context: "naev/naev-macos"
            imagename: "naev-macos"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/projectsynchro/${{ matrix.imagename }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
