name: Naev Infrastructure Testing
on: [push, pull_request]

jobs:
  "Build_Test_Images":
    strategy:
      fail-fast: true
      matrix:
        include:
#          - context: "naev-linux-archaic"
#            imagename: "naev-linux-archaic"
#          - context: "naev-linux-lts"
#            imagename: "naev-linux-lts"
#          - context: "naev-linux-latest"
#            imagename: "naev-linux-latest"
#          - context: "naev-steamruntime"
#            imagename: "naev-steamruntime"
          - context: "naev-windows"
            imagename: "naev-windows"
#          - context: "naev-macos"
#            imagename: "naev-macos"

    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/naev/${{ matrix.imagename }}

      - name: Build and push
        uses: elgohr/Publish-Docker-Github-Action@v5
        id: docker_build
        with:
          name: ghcr.io/naev/${{ matrix.imagename }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          context: ${{ matrix.context }}
          dockerfile: ${{ matrix.context }}/Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          no_push: true
